### ISSUE TITLE
selinux-support.yml is not used

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [lean-delivery/ansible-role-jenkins#12]
##### SUMMARY
selinux-support.yml is not used - tasks/main.yml or any other yml doesn't call it.
It should be called from RedHat.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
selinux-support.yml

**Comment by ibarysev** [comment]
https://github.com/lean-delivery/ansible-role-jenkins/pull/29
Merged
