### ISSUE TITLE
Add installation on Windows

### ISSUE THREAD

**Issue by ViachaslauKabak** [lean-delivery/ansible-role-jenkins#23]

**Comment by tgadiev** [comment]
@ViachaslauKabak pls take a look if it's done

**Comment by Densoff** [comment]
According https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-i-run-python-modules we are not able to use as is some features in tasks/ and handlers/. So, I guess we can't do code refactoring and have to make some new features for windows or don't use them. Another possible solution is set dependencies to the windows hosts with Python installation. But it needs testing.

**Comment by tgadiev** [comment]
Better handle this with a separate role for Windows installation
