### ISSUE TITLE
Fix ssh username with private key credentials

### ISSUE THREAD

**Issue by vnovichek** [lean-delivery/ansible-role-jenkins#31]
##### SUMMARY
There is an implementation bug with private key credentials. The private key is saved as a long single string with -----BEGIN RSA PRIVATE KEY----- header, body and -----END RSA PRIVATE KEY----- footer.
The problem is header and footer must be separated from body with '\n' (not a space or two symbols '\' + 'n').

##### COMPONENT NAME
templates/set-credentials.groovy.j2

**Comment by tgadiev** [comment]
@vnovichek is bug still in place?
